version: 2
jobs:
   build:
     docker:
       - image: circleci/node:carbon
     steps:
       - checkout
       - run: echo "Hello world"
    publish:
      docker:
        - image: circleci/node:carbon
      steps:
        - checkout

workflows:
  version: 2
  build:
    jobs:
      - build
